import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/anime/providerComponent';
import { AppSidebar } from '@/components/layout/appSidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <body className="min-h-full flex flex-row h-screen w-screen overflow-hidden">
        <AppSidebar />
        <Providers>
          <main className="flex-1 h-full min-w-0 overflow-y-auto p-6">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
